CREATE TABLE ADRESS (ADD_LOC varchar(255) NOT NULL, ID_ADD SERIAL NOT NULL, DIS_ADD varchar(255) NOT NULL, NUM_ADD varchar(20) NOT NULL, ID_STA int4 NOT NULL, ID_PER int4 NOT NULL, PRIMARY KEY (ID_ADD));
COMMENT ON TABLE ADRESS IS 'Endereço da pessoa';
COMMENT ON COLUMN ADRESS.ADD_LOC IS 'RUA';
COMMENT ON COLUMN ADRESS.ID_ADD IS 'PRIMARY KEY DOS ENDEREÇOS';
COMMENT ON COLUMN ADRESS.DIS_ADD IS 'BAIRRO';
COMMENT ON COLUMN ADRESS.NUM_ADD IS 'NUMERO RESIDENCIAL';
ALTER TABLE ADRESS ADD CONSTRAINT FKADRESS125057 FOREIGN KEY (ID_PER) REFERENCES PERSON (ID_PER);
ALTER TABLE ADRESS ADD CONSTRAINT FKADRESS740676 FOREIGN KEY (ID_STA) REFERENCES STATE (ID_STA);