CREATE TABLE PERSON_SYMPTOMS (ID_PER int4 NOT NULL, ID_SYM int4 NOT NULL, DAT_SYM date NOT NULL, DAT_CUR date, PRIMARY KEY (ID_PER, ID_SYM));
COMMENT ON COLUMN PERSON_SYMPTOMS.DAT_CUR IS 'DATA DA CURA';
ALTER TABLE PERSON_SYMPTOMS ADD CONSTRAINT FKPERSON_SYM805810 FOREIGN KEY (ID_SYM) REFERENCES SYMPTOMS (ID_SYM);
ALTER TABLE PERSON_SYMPTOMS ADD CONSTRAINT FKPERSON_SYM685606 FOREIGN KEY (ID_PER) REFERENCES PERSON (ID_PER);