CREATE TABLE SYMPTOMS (ID_SYM SERIAL NOT NULL, DES_SYM varchar(255) NOT NULL, INT_SYM char(1) NOT NULL, PRIMARY KEY (ID_SYM));
COMMENT ON TABLE SYMPTOMS IS 'TABELA DE SINTOMAS DO PACIENTE';
COMMENT ON COLUMN SYMPTOMS.DES_SYM IS 'DESCRIÇÃO DO SINTOMA';
COMMENT ON COLUMN SYMPTOMS.INT_SYM IS 'INTENSIDADE DO SINTOMA